POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjY4MzU5OWQ4OWQ4YWQyODJhYjVkNDQ4MCIsImlhdCI6MTc0ODM0MzI2MCwiZXhwIjoxNzQ4MzQ2ODYwfQ.MAA4gZQifsea8RjeAEgLLQEIacuOaqiItGJSQw1pCgU

{
  "title": "My first blog post",
  "author": "John Doe",
  "url": "https://example.com/my-first-blog-post",
  "likes": 10
}